apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: website-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTP
    hosts:
    - "{{ .Values.host }}"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: website
spec:
  hosts:
  - "{{ .Values.host }}"
  gateways:
  - website-gateway
  http:
  - route:
    - destination:
        host: website.{{ .Values.clusterName }}.svc.cluster.local
